#!/usr/bin/env python3

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import argparse
from pathlib import Path

from firma.util.env import load_env_app



def main():
    parser = argparse.ArgumentParser(
        description="Print .env variables.")

    parser.add_argument(
        "--env", "-E",
        action="store", dest="env_path",
        type=Path,
        default=Path("."),
        help="Path to directory of .env files.")
    parser.add_argument(
        "--mode", "-M",
        action="store",
        help="Application mode.")

    parser.add_argument(
        "--makefile-include",
        action="store_true",
        help="Print all variables in GNU Makefile format.")

    parser.add_argument(
        "key",
        metavar="KEY",
        action="store",
        nargs="?",
        help="Variable name.")

    args = parser.parse_args()

    if not (args.makefile_include or args.key):
        sys.stderr.write("Error: either `--makefile-include` or a variable KEY name are required.\n\n")
        sys.stderr.flush()
        parser.print_usage()
        sys.exit(1)

    env = load_env_app(args.env_path, mode=args.mode)

    if args.makefile_include:
        for k, v in env.items():
            print(f"{k} := {v}")
        return

    value = env.get(args.key, None)
    if value is not None:
        print(value)



if __name__ == "__main__":
    main()
